name: Docker Build & Push - V2

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. Récupérer le code
      - name: Checkout code
        uses: actions/checkout@v4

      # --- ÉTAPE AJOUTÉE (Celle qui manquait !) ---
      # Installe l'outil "Buildx" nécessaire pour construire l'image correctement
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 2. Se connecter à DockerHub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3. Construire et Pousser
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/student-registry-v2:latest
          # On active le cache pour que ça aille plus vite les prochaines fois
          cache-from: type=gha
          cache-to: type=gha,mode=max